import order from 'stylelint-order';
import scss from 'stylelint-scss';

export default {
  plugins: [order, scss, 'stylelint-declaration-strict-value'],
  extends: ['stylelint-config-standard-scss', 'stylelint-config-prettier-scss'],
  rules: {
    'no-empty-source': null,
    'color-hex-length': 'short',
    'max-nesting-depth': 3,
    'order/properties-alphabetical-order': null,
    'order/properties-order': [
      [
        // Position
        {
          groupName: 'position',
          properties: ['position', 'inset', 'top', 'right', 'bottom', 'left', 'z-index'],
        },
        // Box model
        {
          groupName: 'box-model',
          properties: [
            'display',
            'visibility',
            'float',
            'clear',
            'box-sizing',
            'flex',
            'flex-grow',
            'flex-shrink',
            'flex-basis',
            'flex-direction',
            'flex-wrap',
            'justify-content',
            'align-items',
            'align-content',
            'align-self',
            'order',
            'grid',
            'grid-template',
            'grid-template-areas',
            'grid-template-columns',
            'grid-template-rows',
            'grid-auto-flow',
            'grid-auto-columns',
            'grid-auto-rows',
            'grid-column',
            'grid-row',
            'gap',
            'width',
            'min-width',
            'max-width',
            'height',
            'min-height',
            'max-height',
            'margin',
            'margin-top',
            'margin-right',
            'margin-bottom',
            'margin-left',
            'padding',
            'padding-top',
            'padding-right',
            'padding-bottom',
            'padding-left',
            'overflow',
            'overflow-x',
            'overflow-y',
          ],
        },
        // Border + background
        {
          groupName: 'border-background',
          properties: [
            'border',
            'border-width',
            'border-style',
            'border-color',
            'border-top',
            'border-right',
            'border-bottom',
            'border-left',
            'border-radius',
            'outline',
            'outline-width',
            'outline-style',
            'outline-color',
            'outline-offset',
            'background',
            'background-color',
            'background-image',
            'background-repeat',
            'background-position',
            'background-size',
            'background-clip',
            'background-origin',
            'background-attachment',
            'box-shadow',
          ],
        },
        // Typography / visual styles
        {
          groupName: 'styles',
          properties: [
            'color',
            'font',
            'font-family',
            'font-size',
            'font-weight',
            'font-style',
            'line-height',
            'letter-spacing',
            'text-align',
            'text-transform',
            'text-decoration',
            'text-overflow',
            'white-space',
            'word-break',
            'opacity',
          ],
        },
      ],
      { unspecified: 'bottomAlphabetical' },
    ],
    'scss/load-partial-extension': 'never',
    'scss/dollar-variable-pattern': '^[_a-z][a-zA-Z0-9-]+$',
    'scss/percent-placeholder-pattern': '^[_a-z][a-zA-Z0-9-]+$',
    'selector-pseudo-element-no-unknown': [
      true,
      {
        ignorePseudoElements: [
          'webkit-input-placeholder',
          'moz-input-placeholder',
          'ms-input-placeholder',
          'input-placeholder',
        ],
      },
    ],
    'selector-pseudo-class-no-unknown': [
      true,
      {
        ignorePseudoClasses: ['input-placeholder', 'moz-input-placeholder'],
      },
    ],
    'property-no-deprecated': [
      true,
      {
        ignoreProperties: ['clip'],
      },
    ],
    'scale-unlimited/declaration-strict-value': [
      ['/color/'],
      {
        ignoreValues: ['inherit', 'transparent', 'currentColor', 'none', '/^#([0-9a-fA-F]{3,8})$/'],
        disableFix: false,
      },
    ],
  },
  ignoreFiles: ['**/*.js', '**/*.ts', '**/*.tsx', '**/*.svg', 'node_modules/**', 'dist/**'],
};
